// Run against an isolated app; artifacts and synthetic fixtures stay outside Git.
const {chromium}=require('../web/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.LIBRARY_QA_URL||'http://127.0.0.1:60055',dir=process.env.LIBRARY_QA_OUTPUT;
assert(dir,'Set LIBRARY_QA_OUTPUT to an isolated synthetic output directory.');
(async()=>{const browser=await chromium.launch({...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('header .project-switch select:enabled').waitFor();
 // Old optional PDF path, without creating or assigning a library.
 await page.locator('header').getByRole('button',{name:'Новая',exact:true}).click();await page.getByLabel('Название',{exact:true}).fill('UI independent ready PDFs '+Date.now());await page.getByRole('button',{name:'Создать',exact:true}).click();
 await page.locator('.modal-backdrop').waitFor({state:'hidden'});await page.waitForFunction(()=>!document.querySelector('input[aria-label="Добавить готовые PDF"]').disabled);await page.getByLabel('Добавить готовые PDF',{exact:true}).setInputFiles(path.join(dir,'fixtures','Material 000.pdf'));await page.locator('.row-button').waitFor();await page.getByRole('button',{name:/Проверка и экспорт/}).click();let downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Собрать подачу · ZIP',exact:true}).click();await(await downloading).saveAs(path.join(dir,'ui-independent.zip'));
 await page.getByRole('button',{name:'Библиотеки дел',exact:true}).click();const dlg=page.locator('.library-dialog');const name='UI bulk '+Date.now();await dlg.getByLabel('Название новой библиотеки').fill(name);await dlg.getByRole('button',{name:'Создать библиотеку',exact:true}).click();await page.waitForFunction(n=>document.querySelector('.library-dialog select[aria-label="Библиотека"]')?.selectedOptions[0]?.text===n,name);
 const lid=await dlg.getByLabel('Библиотека',{exact:true}).inputValue();await dlg.locator('.library-upload summary').click();const files=fs.readdirSync(path.join(dir,'fixtures')).filter(n=>n.endsWith('.pdf')).map(n=>path.join(dir,'fixtures',n));assert.equal(files.length,100);
 await page.evaluate(()=>{window._libraryFeedbackStart=performance.now();new MutationObserver((_,o)=>{if(document.querySelector('.library-upload').textContent.includes('Загрузка PDF:')){window._libraryFeedback=performance.now()-window._libraryFeedbackStart;o.disconnect();}}).observe(document.querySelector('.library-upload'),{childList:true,subtree:true});});
 await page.waitForFunction(()=>!document.querySelector('input[aria-label="PDF для библиотеки"]').disabled);await dlg.getByLabel('PDF для библиотеки').setInputFiles(files);await dlg.getByText('PDF проверены. Укажите роли и состав перед сохранением.',{exact:true}).waitFor({timeout:120000});const feedback=await page.evaluate(()=>window._libraryFeedback);assert(feedback<=300,{feedback});
 await dlg.getByRole('button',{name:'Все PDF как готовые',exact:true}).click();const metadataRow=dlg.locator('.library-upload tbody tr').first();await metadataRow.locator('summary').click();await metadataRow.getByLabel('Категория',{exact:true}).fill('Evidence');await metadataRow.getByLabel('Язык',{exact:true}).fill('Русский');await metadataRow.getByLabel('Метки через запятую',{exact:true}).fill('blue, юникод');await metadataRow.getByLabel('Дата документа',{exact:true}).fill('2026-10-09');await dlg.getByRole('button',{name:'Проверить наполнение',exact:true}).click();await dlg.getByRole('heading',{name:'Состав библиотеки перед сохранением'}).waitFor({timeout:60000});await dlg.getByRole('button',{name:'Сохранить выбранные PDF в библиотеку',exact:true}).click();await dlg.getByText('Материалы сохранены.',{exact:true}).waitFor({timeout:60000});await dlg.locator('.library-upload summary').click();
 // Search/filter, three-row assignments, stable number proposal and atomic import.
 await dlg.getByRole('button',{name:'Отметить эту страницу',exact:true}).click();assert.equal(await dlg.getByLabel('Добавить в подачу',{exact:true}).count(),50);assert.equal(await dlg.getByRole('button',{name:'Добавить выбранные · 50',exact:true}).count(),1);await dlg.getByRole('button',{name:'Снять все отметки',exact:true}).click();assert.equal(await dlg.getByRole('button',{name:'Добавить выбранные · 0',exact:true}).count(),1);
 await dlg.locator('.library-filters summary').click();const filters=dlg.locator('.library-filters');await filters.getByLabel('Категория',{exact:true}).fill('Evidence');await filters.getByLabel('Язык',{exact:true}).fill('Русский');await filters.getByLabel('Дата документа',{exact:true}).fill('2026-10-09');await filters.getByLabel('Метка',{exact:true}).fill('юникод');await page.waitForFunction(()=>document.querySelector('.library-items')?.querySelectorAll('article').length===1);for(const label of ['Категория','Язык','Дата документа','Метка'])await filters.getByLabel(label,{exact:true}).fill('');await dlg.locator('.library-filters summary').click();
 await dlg.getByLabel('Поиск по названию или имени файла').fill('Material 00');await dlg.locator('.library-items article').nth(2).waitFor();for(let i=0;i<3;i++)await dlg.getByLabel('Добавить в подачу',{exact:true}).nth(i).check();await dlg.getByRole('button',{name:/Добавить выбранные/}).click();await dlg.getByLabel('Режим для всех выбранных',{exact:true}).selectOption('passthrough');await dlg.getByRole('button',{name:'Применить режим ко всем',exact:true}).click();await dlg.getByLabel('Общая папка',{exact:true}).fill('Evidence/Материалы');await dlg.getByRole('button',{name:'Задать папку всем',exact:true}).click();for(const title of ['Material 000','Material 001','Material 002']){assert.equal(await dlg.getByLabel('Режим '+title,{exact:true}).inputValue(),'passthrough');assert.equal(await dlg.getByLabel('Папка '+title,{exact:true}).inputValue(),'Evidence/Материалы');}await page.setViewportSize({width:390,height:1000});assert(await dlg.evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.screenshot({path:path.join(dir,'bulk-assignments-390.png')});await page.setViewportSize({width:1440,height:1000});await dlg.getByRole('button',{name:'Проверить назначения',exact:true}).click();await dlg.getByText('Назначения проверены.',{exact:false}).waitFor();await dlg.getByRole('button',{name:'Добавить в подачу',exact:true}).click();await dlg.getByText('Материалы добавлены.',{exact:false}).waitFor();
 await dlg.locator('.library-items .title-button').first().click();await dlg.locator('.material-preview').waitFor();await dlg.getByRole('button',{name:/Где используется/}).click();await dlg.getByText('Только подачи в папке данных',{exact:false}).waitFor();await dlg.getByRole('button',{name:'Скрыть материал из каталога',exact:true}).click();await dlg.locator('.library-filters summary').click();await dlg.getByLabel('Показать скрытые материалы').check();await dlg.locator('.library-items .title-button').first().click();await dlg.getByRole('button',{name:'Вернуть материал в каталог',exact:true}).click();await dlg.getByLabel('Показать скрытые материалы').uncheck();await dlg.locator('.library-items .title-button').first().click();await dlg.getByRole('button',{name:/Где используется/}).click();await dlg.locator('section').getByRole('button',{name:/UI independent ready PDFs.*Annex 1/}).click();await dlg.waitFor({state:'hidden'});await page.getByRole('button',{name:'Библиотеки дел',exact:true}).click();await dlg.getByLabel('Библиотека',{exact:true}).selectOption(lid);await dlg.locator('.library-items article').first().waitFor();
 for(const width of [1440,760,390]){await page.setViewportSize({width,height:1000});assert(await dlg.evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.screenshot({path:path.join(dir,`bulk-${width}.png`)});}
 await page.keyboard.press('Escape');assert.equal(await page.locator('.library-dialog').count(),0);assert.equal(await page.getByRole('button',{name:'Библиотеки дел',exact:true}).evaluate(e=>e===document.activeElement),true);
 await page.getByRole('button',{name:/Проверка и экспорт/}).click();downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Собрать подачу · ZIP',exact:true}).click();await(await downloading).saveAs(path.join(dir,'ui-bulk.zip'));
 // Two independent local conflicts remain visible until one final re-comparison.
 const api=async(route,body)=>{const response=body===undefined?await page.request.get(base+'/api'+route):await page.request.post(base+'/api'+route,{data:body,headers:{'X-Exhibit-Local':'1'}});assert(response.ok(),await response.text());return response.json();};
 const operation=async(action,args)=>{const job=await api('/material-operations',{action,arguments:args});for(let i=0;i<600;i++){const state=await api('/material-operations/'+job.id);if(state.state==='complete')return state.result;assert(!['error','cancelled','interrupted'].includes(state.state),state.message);await new Promise(r=>setTimeout(r,100));}throw Error('Operation timed out');};
 const pid=await page.getByLabel('Проект',{exact:true}).inputValue(),project=await api('/projects/'+pid),doc=project.documents.find(d=>d.provenance);assert(doc);
 const preview=await operation('save_preview',{lid,pid,rows:[{document_id:doc.id,material_id:doc.provenance.material_id,allow_duplicate:true,metadata:{title:'Library revised title',short_title:'Library revised short'}}]});await operation('publish',{token:preview.token});
 await api(`/projects/${pid}/documents/${doc.id}`,{title:'Local title',short_title:'Local short'});await page.reload();await page.getByRole('button',{name:'Проверить версии материалов',exact:true}).click();
 await dlg.locator('.library-source').filter({hasText:'Local title'}).getByRole('button',{name:'Выбрать версию для обновления'}).click();await dlg.getByRole('button',{name:'Сравнить с местной копией'}).click();
 await dlg.getByLabel('Решение Название',{exact:true}).selectOption('local');await dlg.getByLabel('Решение Краткое название',{exact:true}).selectOption('library');assert(await dlg.getByRole('button',{name:'Применить к выбранному приложению'}).isDisabled());
 await dlg.getByRole('button',{name:'Сравнить с местной копией'}).click();await dlg.getByRole('button',{name:'Применить к выбранному приложению'}).click();await dlg.getByText('Обновление применено.',{exact:false}).waitFor();
 const updated=(await api('/projects/'+pid)).documents.find(d=>d.id===doc.id);assert.equal(updated.title,'Local title');assert.equal(updated.short_title,'Library revised short');assert.equal(updated.number,doc.number);await page.keyboard.press('Escape');
 assert.deepEqual(errors,[]);const proof={result:'passed',ui_pdf_count:100,bulk_import:3,old_independent_path:true,usage_hide_return:true,combined_metadata_filters:true,usage_navigation:true,multiple_local_conflicts:true,page_selection_and_common_assignments:true,keyboard_escape_and_focus:true,feedback_ms:feedback,viewports:[1440,760,390],errors,lid};fs.writeFileSync(path.join(dir,'bulk-ui-report.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
