// Actual Chromium UI against an isolated synthetic server; no native desktop takeover.
const {chromium}=require('../web/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.LIBRARY_QA_URL,dir=process.env.LIBRARY_QA_OUTPUT;assert(base&&dir);
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const api=async(route,body,raw)=>{const r=body===undefined&&raw===undefined?await page.request.get(base+'/api'+route):await page.request.post(base+'/api'+route,{...(raw?{data:raw}:{data:body}),headers:{'X-Exhibit-Local':'1'}});assert(r.ok(),await r.text());return r.json();};
 const operation=async(action,args)=>{const j=await api('/material-operations',{action,arguments:args});for(let i=0;i<900;i++){const s=await api('/material-operations/'+j.id);if(s.state==='complete')return s.result;assert(!['error','cancelled','interrupted'].includes(s.state),s.message);await new Promise(r=>setTimeout(r,100));}throw Error('Timed out');};
 const lib=await api('/libraries',{name:'Review historical matches '+Date.now()}),files=Array.from({length:100},(_,i)=>path.join(dir,'fixtures',`Material ${String(i).padStart(3,'0')}.pdf`));
 const rows=[];for(let i=0;i<100;i++){const u=await api('/library-files?name='+encodeURIComponent(path.basename(files[i])),undefined,fs.readFileSync(files[i]));rows.push({token:u.token,role:'ready',metadata:{title:i===90?'ZZZ Historical material':`Catalog ${String(i).padStart(3,'0')}`}});}
 const seed=await operation('upload_preview',{lid:lib.id,rows}),saved=await operation('publish',{token:seed.token}),target=saved.materials[90];
 const changed=await api('/library-files?name=New-version.pdf',undefined,fs.readFileSync(files[1]));const second=await operation('upload_preview',{lid:lib.id,rows:[{token:changed.token,role:'ready',material_id:target.material_id,metadata:{title:'ZZZ Historical material'},allow_duplicate:true}]});await operation('publish',{token:second.token});
 const beforeCard=await api(`/libraries/${lib.id}/materials/${target.material_id}`);assert.equal(beforeCard.versions.length,2);
 await page.goto(base);await page.locator('header .project-switch select:enabled').waitFor();await page.getByRole('button',{name:'Библиотеки дел',exact:true}).click();const dlg=page.locator('.library-dialog');await dlg.getByLabel('Библиотека',{exact:true}).selectOption(lib.id);await dlg.locator('.library-items article').first().waitFor();assert.equal(await dlg.locator('.library-items').getByText('ZZZ Historical material',{exact:true}).count(),0);
 await dlg.locator('.library-upload summary').click();await dlg.getByLabel('PDF для библиотеки').setInputFiles(['Historical copy.pdf','Batch copy.pdf'].map(name=>({name,mimeType:'application/pdf',buffer:fs.readFileSync(files[90])})));
 await dlg.getByText('PDF проверены. Укажите роли и состав перед сохранением.',{exact:true}).waitFor();await dlg.getByRole('button',{name:'Все PDF как готовые',exact:true}).click();await dlg.getByRole('button',{name:'Проверить наполнение',exact:true}).click();await dlg.getByRole('heading',{name:'Состав библиотеки перед сохранением'}).waitFor();
 const duplicateRows=dlg.locator('.library-upload .duplicate-row');await duplicateRows.first().getByText('«ZZZ Historical material» · версия 1',{exact:true}).waitFor();assert(await dlg.getByRole('button',{name:'Сохранить выбранные PDF в библиотеку',exact:true}).isDisabled());
 await duplicateRows.first().getByRole('button',{name:'Посмотреть совпавшую версию',exact:true}).click();await dlg.locator('.material-card .material-preview').waitFor();assert.equal(await dlg.locator('.material-card select').first().inputValue(),target.version_id);
 await duplicateRows.first().getByRole('button',{name:'Использовать существующий материал',exact:true}).click();
 const batch=duplicateRows.nth(1).locator('.duplicate-match').filter({hasText:'в этой загрузке'});await batch.getByRole('button',{name:'Посмотреть совпавшую версию',exact:true}).click();await dlg.getByAltText('Совпадение: Historical copy').waitFor();await dlg.getByRole('button',{name:'Закрыть просмотр совпадения',exact:true}).click();await batch.getByRole('button',{name:'Сохранить новую версию этого материала',exact:true}).click();
 for(const width of [1440,760,390]){await page.setViewportSize({width,height:1000});assert(await dlg.evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.screenshot({path:path.join(dir,`review-duplicates-${width}.png`),fullPage:false});}
 await page.setViewportSize({width:1440,height:1000});await dlg.getByRole('button',{name:'Сохранить выбранные PDF в библиотеку',exact:true}).click();await dlg.getByText('Решения применены. Найденные версии доступны для добавления в подачу.',{exact:true}).waitFor();
 assert.equal((await api(`/libraries/${lib.id}/materials`)).total,100);assert.equal((await api(`/libraries/${lib.id}/materials/${target.material_id}`)).versions.length,3);
 // Separate material is a third explicit choice, without an unnamed catalog search.
 await dlg.getByLabel('PDF для библиотеки').setInputFiles({name:'Separate copy.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(files[90])});await dlg.getByText('PDF проверены. Укажите роли и состав перед сохранением.',{exact:true}).waitFor();await dlg.getByRole('button',{name:'Все PDF как готовые',exact:true}).click();await dlg.getByRole('button',{name:'Проверить наполнение',exact:true}).click();await dlg.getByRole('heading',{name:'Состав библиотеки перед сохранением'}).waitFor();await dlg.getByRole('button',{name:'Сохранить отдельный материал',exact:true}).click();await dlg.getByRole('button',{name:'Сохранить выбранные PDF в библиотеку',exact:true}).click();await dlg.getByText('Материалы сохранены.',{exact:true}).waitFor();assert.equal((await api(`/libraries/${lib.id}/materials`)).total,101);
 // Saving from a submission uses the same named historical match and real buttons.
 await page.keyboard.press('Escape');const project=await api('/projects',{name:'Review save from submission'});const response=await api(`/projects/${project.id}/upload?mode=passthrough&name=Source.pdf`,undefined,fs.readFileSync(files[90]));await page.reload();await page.getByLabel('Проект',{exact:true}).selectOption(project.id);await page.locator('.row-button').first().click();await page.getByRole('button',{name:'Сохранить в библиотеку',exact:true}).click();await dlg.getByLabel('Библиотека',{exact:true}).selectOption(lib.id);await dlg.getByRole('button',{name:'Проверить состав',exact:true}).click();await dlg.getByRole('heading',{name:'Состав перед сохранением'}).waitFor();const firstMatch=dlg.locator('.library-plan .duplicate-match').filter({hasText:'«ZZZ Historical material» · версия 1'});await firstMatch.getByRole('button',{name:'Посмотреть совпавшую версию',exact:true}).click();await dlg.locator('.material-card .material-preview').waitFor();await firstMatch.getByRole('button',{name:'Использовать существующий материал',exact:true}).click();await dlg.getByRole('button',{name:'Сохранить материалы',exact:true}).click();await dlg.getByText('Решения применены. Исходная подача не изменена.',{exact:true}).waitFor();assert.deepEqual((await api('/projects/'+project.id)).documents,response.documents);
 await page.keyboard.press('Escape');assert.deepEqual(errors,[]);const proof={result:'passed',browser:'Chromium',browser_plugin:'not available',historical_match_off_page:true,named_version_preview:true,reuse_without_new_copy:true,new_version:true,separate_material:true,batch_resolution:true,save_from_submission:true,viewports:[1440,760,390],errors};fs.writeFileSync(path.join(dir,'review-ui-report.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
