import React,{useEffect,useRef,useState} from 'react';

function download(token){const a=document.createElement('a');a.href=`/api/library-archives/${token}/download`;a.download='Exhibit-library.zip';a.click();}

export default function LibraryArchive({api,lid,run,blocked,onRestored}) {
  const [preview,setPreview]=useState(null),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[notice,setNotice]=useState('');
  const controller=useRef(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  async function upload(file){if(!file)return;setUploading(true);setPreview(null);setError('');controller.current=new AbortController();try{const result=await api(`/library-files?archive=true&name=${encodeURIComponent(file.name)}`,file,{signal:controller.current.signal});await run('archive_preview',{token:result.token},setPreview);}catch(e){setError(controller.current.signal.aborted?'Загрузка архива отменена. Библиотеки не изменены.':e.message);}finally{setUploading(false);}}
  return <details className="library-archives"><summary>Архив библиотеки и перенос на другой компьютер</summary><p>Архив библиотеки содержит все материалы и версии. Архив подачи сохраняет только собственные файлы подачи. Переводчики и панель Word для восстановления не нужны.</p><div className="actions"><button disabled={blocked||uploading||!lid} onClick={()=>run('archive_save',{lid},async r=>{download(r.token);setNotice(`Архив библиотеки сохранён: материалов ${r.summary.materials}, версий ${r.summary.versions}, ${(r.summary.bytes/1e6).toFixed(1)} МБ.`);})}>Сохранить архив библиотеки</button><label className="upload button">Выбрать архив библиотеки<input aria-label="Выбрать архив библиотеки" type="file" accept=".zip" disabled={blocked||uploading} onChange={e=>{const f=e.target.files[0];e.target.value='';upload(f);}}/></label></div>{uploading&&<><p role="status">Загружаем архив для проверки…</p><button disabled={blocked} onClick={()=>controller.current?.abort()}>Отменить загрузку архива</button></>}{error&&<p className="error-note" role="alert">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}{preview&&<section><h3>Восстановить «{preview.name}»</h3><p>Материалов: {preview.summary.materials}. Версий: {preview.summary.versions}. Размер: {(preview.summary.bytes/1e6).toFixed(1)} МБ.</p>{preview.conflict&&<p className="pending">Эта библиотека уже существует. Независимая копия получит новые источники и не переназначит существующие подачи.</p>}<button disabled={blocked||uploading} onClick={()=>run('archive_restore',{token:preview.token,copy:preview.conflict},async r=>{await onRestored(r.id);setPreview(null);setNotice('Библиотека восстановлена. Существующие подачи не изменены.');})}>{preview.conflict?'Восстановить независимую копию':'Восстановить библиотеку'}</button><button disabled={blocked} onClick={()=>setPreview(null)}>Отменить восстановление</button></section>}</details>;
}
