import React, {useRef, useState} from 'react';

export default function TranslationSource({p,doc,options,onChange,disabled,onPreview,source,changed,compact}) {
  const [page,setPage]=useState(1),[drawing,setDrawing]=useState(false),[rect,setRect]=useState(null),[range,setRange]=useState('');
  const start=useRef(null),surface=useRef(null);
  const [markNotes,setMarkNotes]=useState(false);
  const selection=options.selection;
  const h=doc.original.sizes[page-1][1];
  const preserve=options.placement==='preserve';
  const notesHeight=options.notes?.find(x=>x.page===page)?.height||0;
  function setNotes(height){onChange({...options,notes:[...(options.notes||[]).filter(x=>x.page!==page),{page,height}].sort((a,b)=>a.page-b.page)});}
  function point(e){const b=surface.current.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))];}
  function move(e){if(!start.current)return;const [x,y]=point(e),[sx,sy]=start.current;setRect([Math.min(x,sx),Math.min(y,sy),Math.max(x,sx),Math.max(y,sy)]);}
  const [error,setError]=useState('');
  function applyRange(){try{const result=[];for(const token of range.split(',')){const m=/^\s*(\d+)(?:\s*-\s*(\d+))?\s*$/.exec(token);if(!m)throw Error('Укажите страницы, например 1, 3-5.');const a=Number(m[1]),b=Number(m[2]||m[1]);if(a<1||b<a||b>doc.original.pages)throw Error('Страницы вне документа.');for(let n=a;n<=b;n++)if(!result.some(x=>x.page===n))result.push({page:n});}onChange({...options,selection:result});setError('');}catch(e){setError(e.message);}}
  function update(key,value){onChange({...options,[key]:value});}
  return <details className="translation-source-picker" open={!compact}><summary>Что отправить на перевод</summary><fieldset disabled={disabled}>
    <p className="muted">Выберите страницы или нарисуйте области. Это отдельный выбор для перевода; состав итогового приложения задаётся в основном окне.</p>
    <div className="actions"><input aria-label="Страницы для перевода" placeholder="Например: 1, 3-5" value={range} onChange={e=>setRange(e.target.value)}/><button onClick={applyRange}>Выбрать страницы</button><button onClick={()=>update('selection',Array.from({length:doc.original.pages},(_,i)=>({page:i+1})))}>Все страницы</button><button onClick={()=>update('selection',[])}>Очистить выбор</button></div>
    <label className="field"><span>Сноски и колонтитулы</span><select value={preserve?'preserve':'exclude'} onChange={e=>onChange({...options,placement:e.target.value,notes:options.notes||[]})}><option value="preserve">Перевести и сохранить расположение</option><option value="exclude">Исключить верхнюю и нижнюю зоны</option></select></label>
    <p className="muted">{preserve?'Жёлтые зоны — колонтитулы, оранжевая — сноски. Они переводятся отдельно и остаются сверху/снизу той же страницы. Укажите высоту области сносок для каждой страницы с примечаниями: автоматического распознавания сносок нет.':'Серые зоны исключаются из отправки. Текст между ними переводится как основной.'} Границы должны проходить между строками. 60 pt ≈ 21 мм.</p>
    <div className="actions"><label>{preserve?'Верхний колонтитул, pt':'Исключить сверху, pt'} <input aria-label={preserve?'Верхний колонтитул, pt':'Исключить сверху, pt'} type="number" min="0" max="200" value={options.top} onChange={e=>update('top',Number(e.target.value))}/></label><label>{preserve?'Нижний колонтитул, pt':'Исключить снизу, pt'} <input aria-label={preserve?'Нижний колонтитул, pt':'Исключить снизу, pt'} type="number" min="0" max="200" value={options.bottom} onChange={e=>update('bottom',Number(e.target.value))}/></label>{!preserve?<button onClick={()=>onChange({...options,top:0,bottom:0})}>Включить весь текст страницы</button>:null}</div>
    <div className="source-picker-columns"><section><div className="actions"><button aria-label="Предыдущая страница выбора" disabled={disabled||page<=1} onClick={()=>{setPage(page-1);setRect(null);}}>←</button><span>Страница {page} / {doc.original.pages}</span><button aria-label="Следующая страница выбора" disabled={disabled||page>=doc.original.pages} onClick={()=>{setPage(page+1);setRect(null);}}>→</button><button className={drawing?'active':''} onClick={()=>{setDrawing(!drawing);setRect(null);}}>Выделить область для перевода</button></div>
      {preserve?<><label className="field"><span>Область сносок на странице {page}, pt</span><input aria-label="Высота области сносок, pt" type="number" min="0" max="400" value={notesHeight} onChange={e=>setNotes(Number(e.target.value))}/><small>Высота над нижним колонтитулом. 0 — сносок нет. Верхняя граница должна быть над первой строкой сноски.</small></label><button className={markNotes?'active':''} onClick={()=>{setMarkNotes(!markNotes);setDrawing(false);setRect(null);}}>Указать начало сносок на странице</button>{markNotes?<p role="status">Щёлкните на странице между основным текстом и первой сноской. Оранжевая зона должна включать все сноски.</p>:null}</>:null}
      <div className={'source-paper '+(drawing||markNotes?'drawing':'')} ref={surface} onPointerDown={e=>{if(disabled)return;if(markNotes&&preserve){const height=Math.round(h*(1-point(e)[1])-options.bottom);if(height<0||height>400){setError('Выберите границу над нижним колонтитулом, не выше 400 pt от него.');return;}setNotes(height);setMarkNotes(false);setError('');return;}if(!drawing)return;start.current=point(e);surface.current.setPointerCapture(e.pointerId);setRect(null);}} onPointerMove={move} onPointerUp={e=>{move(e);start.current=null;}} onPointerCancel={()=>{start.current=null;setRect(null);}}>
        <img draggable="false" alt={`Выбор для перевода, страница ${page}`} src={`/api/projects/${p.id}/documents/${doc.id}/preview?part=original&page=${page}&v=${doc.original.sha256}`}/>
        {selection.filter(x=>x.page===page).map((x,i)=>{const r=x.rect||[0,0,1,1];return <div key={i} className="source-included" style={{left:r[0]*100+'%',top:r[1]*100+'%',width:(r[2]-r[0])*100+'%',height:(r[3]-r[1])*100+'%'}}/>;})}
        <div className={preserve?'source-furniture':'source-excluded'} style={{top:0,height:Math.min(100,options.top/h*100)+'%'}}/><div className={preserve?'source-furniture':'source-excluded'} style={{bottom:0,height:Math.min(100,options.bottom/h*100)+'%'}}/>
        {preserve&&notesHeight>0?<div className="source-notes" style={{bottom:options.bottom/h*100+'%',height:notesHeight/h*100+'%'}}/>:null}
        {rect ? <div className="crop-rect" style={{left:rect[0]*100+'%',top:rect[1]*100+'%',width:(rect[2]-rect[0])*100+'%',height:(rect[3]-rect[1])*100+'%'}}/> : null}
      </div><button disabled={disabled||!rect||rect[2]-rect[0]<.01||rect[3]-rect[1]<.01} onClick={()=>{update('selection',[...selection.filter(x=>x.page!==page||x.rect),{page,rect}]);setRect(null);}}>Добавить область в перевод</button>
    </section><section><h2>Выбранные страницы и области</h2><p className="muted">Добавленная область заменяет целую страницу в выборе. Несколько областей одной страницы можно добавить последовательно. Текст вне областей не отправляется, включая сноски и колонтитулы вне выделения.</p><ol className="selection-list">{selection.map((x,i)=><li key={i}><span>Страница {x.page} · {x.rect?'область':preserve?'целиком, с разделением зон':'без исключённых зон'}{preserve?` · сноски: ${options.notes?.find(n=>n.page===x.page)?.height||0} pt`:''}</span><button aria-label={`Убрать из перевода ${i+1}`} onClick={()=>update('selection',selection.filter((_,n)=>n!==i))}>×</button></li>)}</ol>{!selection.length?<p>Пока ничего не выбрано.</p>:null}<button className="primary" disabled={disabled||!selection.length} onClick={onPreview}>Показать текст для отправки</button><p role="status" className="muted">{changed?'Выбор изменён. Обновите текст и проверьте его перед запуском.':source?'Ниже показан точный текст выбранных областей.':''}</p>{error?<p role="alert">{error}</p>:null}</section></div>
  </fieldset></details>;
}
